title: Wahlbrief - Briefwahl zur Bundestagswahl beantragen
email: contact@wahlbrief.de
description: >-
  Jetzt die Unterlagen zur Briefwahl beantragen: Schnell, bequem und online. Wahlbrief erstellt in 2 Minuten den Online-Antrag.
baseurl: ""
url: "https://staging.wahlbrief.de/"
twitter_username: wahlbrief
github_username: Wahlbrief

# Build settings
plugins:
  - jekyll-multiple-languages-plugin

languages: ["de", "en"]
defaultLang: de
exclude_from_localizations: ["assets"]
default_locale_in_subfolder: false

markdown: kramdown

facebook: "https://www.facebook.com/wahlbrief"
twitter: "https://twitter.com/wahlbrief"
linkedin: "https://www.linkedin.com/company/wahlbrief"
instagram: "https://www.instagram.com/wahlbrief"
