title: Wahlbrief
email: contact@wahlbrief.de
description: >-
  Write an awesome description for your new site here.
baseurl: ""
url: "https://staging.wahlbrief.de/"
twitter_username:
github_username:

# Build settings
plugins:
  - jekyll-multiple-languages-plugin

languages: ["de", "en"]
defaultLang: de
exclude_from_localizations: ["assets"]
default_locale_in_subfolder: false

markdown: kramdown
